name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Poetry
        run: pip3 install poetry --user
        
      - name: Install Dependencies
        run: poetry install

      - name: Test the help page
        run: poetry run yolo-train -h
