name: Ubuntu CI

on: [push, pull_request, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Poetry
        run: |
          python3 -m pip install --upgrade pip
          pip3 install setuptools-rust poetry --user
        
      - name: Install Dependencies
        run: poetry install

      # Prints the help pages of all scripts to see if the imports etc. work
      - name: Test the help pages
        run: | 
          poetry run yolo-train -h
          poetry run yolo-test -h
          poetry run yolo-detect -h

  
